
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/order-service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
server:
  port: 8081